## ESERCIZIO NUMPY - LEZIONE 07/10/2020

### Notebook 02_02 - Array Slicing

Cambiare l’array creandone uno sempre di 10 valori ma che parta da 5 fino a 15

In [1]:
import numpy as np

es1 = np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

1. primi sei valori
2. elementi dopo l’indice 3
3. elementi dopo il terzo elemento
4. subarray con valori 8,9,10,11,12
5. un elemento ogni tre, partendo dal primo
6. un elemento ogni tre partendo dal terzo elemento

In [2]:
#punto1
es1[:6]

array([ 5,  6,  7,  8,  9, 10])

In [3]:
#punto2
print("elemento di indice 3:", es1[3]), 
print("elementi dopo quello di indice 3:", es1[4:])

elemento di indice 3: 8
elementi dopo quello di indice 3: [ 9 10 11 12 13 14]


In [4]:
#punto3
es1[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [5]:
#punto4
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [6]:
#punto5
es1[::3]

array([ 5,  8, 11, 14])

In [7]:
#punto6
es1[1::3]

array([ 6,  9, 12])