# ESERCIZIO PROVA - Lezione del 08-10 (SLIDE 8)
### Subarrays as no-copy views


Creare un array es3 di valori casuali interi (randint) di dimensione 3x3, con valore massimo (incluso) uguale a 20:

1. visualizzare es3

In [23]:
import numpy as np

es3 = np.random.randint(21, size=(3,3))
es3

array([[ 6,  5, 15],
       [10, 16,  4],
       [14, 15, 19]])

2. estrarre il subarray formato dalla seconda riga (es3-sub) come vista e visualizzarlo
3. moltiplicare per 3 tutti gli elementi della seconda colonna di es3
4. visualizzare es3-sub. È cambiato rispetto a prima?
5. estrarre il subarray formato dalla terza colonna di es3 come copia (es3-sub-copy)
6. sommare 10 a tutti gli elementi di es3-sub-copy e visualizzare
7. visualizzare es3. Contiene la modifica del punto 6?

In [15]:
#punto2
es3_sub=es3[1,:]
es3_sub

array([10, 27,  1])

In [24]:
#punto3
print("Valori della colonna prima della moltiplicazione", es3[:,1])
es3[:,1]=es3[:,1]*3
print("Valori della colonna dopo la moltiplicazione", es3[:,1])

Valori della colonna prima della moltiplicazione [ 5 16 15]
Valori della colonna dopo la moltiplicazione [15 48 45]


In [28]:
#punto4: es3_sub è cambiato? 
es3_sub
#Si

array([  10, 2187,    1])

In [31]:
#punto5 (se io faccio la copia ovviamente il mio array originale non si modifica mentre con view si, in questo caso devo mettere .copy())
es3_sub_copy=es3[:,2].copy()
es3_sub_copy

array([15,  4, 19])

In [30]:
#punto6
es3_sub_copy=es3_sub_copy+10
es3_sub_copy

array([25, 14, 29])

In [33]:
#punto7
es3
#non contiene la modifica di es3_sub_copy

array([[ 6, 15, 15],
       [10, 48,  4],
       [14, 45, 19]])

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [38]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

#### Prova di esercizio slide 9 del 08-10

In [34]:
x = np.array([1, 2, 3, 4])
print(x)
# row vector via reshape
x.reshape((2, 2))

[1 2 3 4]


array([[1, 2],
       [3, 4]])

In [35]:
# row vector via newaxis
x[np.newaxis, :2]

array([[1, 2]])

In [36]:
x[np.newaxis, 2:]

array([[3, 4]])

In [40]:
# column vector via reshape
x.reshape((2,2))

array([[1, 2],
       [3, 4]])

# ESERCIZIO PROVA - Lezione del 08-10 (SLIDE 11)
## Array Concatenation and Splitting


### Concatenation of arrays

1. Creare una lista es4 di 36 valori interi crescenti partendo da 1
2. Trasformarlo in un array di dimensione 6x6
3. Estrarre tre subarray di dimensione 2x2 dalle prime due colonne (sub1,
sub2, sub3)
4. Concatenarli (usare concatenate) prima usando axis=0 poi con axis=1
5. Da es4 estrarre un subarray formato dalle prime due righe (sub4)
6. Concatenare sub1 a sub4. Usate hstack o vstack?
7. Trasformate sub4 da 2x6 a 6x2 (le 2 righe diventano 2 colonne)
8. Concatenate sub1, sub2 e sub3 a formare un nuovo array 6x2 (sub5)
9. Concatenate sub4 (trasformato) con sub5. hstack o vstack?

In [41]:
#punto1
import numpy as np

es4=np.arange(1,37)
es4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

You can also concatenate more than two arrays at once:

In [42]:
#punto2
es4=es4.reshape(6,6)
es4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [50]:
#punto3
sub1=es4[:2,:2]
sub1

array([[1, 2],
       [7, 8]])

In [51]:
sub2=es4[2:4,:2]
sub2

array([[13, 14],
       [19, 20]])

In [52]:
sub3=es4[4:6,:2]
sub3

array([[25, 26],
       [31, 32]])

In [53]:
#punto4a
np.concatenate([sub1, sub2, sub3], axis=0)
#axis=0 concatena in verticale

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [54]:
#punto4b
np.concatenate([sub1, sub2, sub3], axis=1)

array([[ 1,  2, 13, 14, 25, 26],
       [ 7,  8, 19, 20, 31, 32]])

In [55]:
#punto5
sub4= es4[:2,:]
sub4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [58]:
#punto6
np.hstack([sub1, sub4]) 
#np.hstack sostituisce np.concatenate h sta per orizzontale

array([[ 1,  2,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  7,  8,  9, 10, 11, 12]])

In [59]:
#punto7
print("sub4 prima di reshape: \n", sub4, "\n")
sub4=sub4.reshape(6,2)
print("sub4 dopo reshape: \n", sub4)

sub4 prima di reshape: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

sub4 dopo reshape: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [60]:
#punto8
sub5=np.vstack([sub1, sub2, sub3])
sub5
#potevo anche usare concatenate con axis=0

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [61]:
#punto9: dato che sub4 e sub5 sono entrambi 6x2 possono concatenarli sia orizziontalmente che verticalmente
print("concateno verticalmente: \n", np.vstack([sub4, sub5]), "\n")
print("concateno orizzontalmente:\n", np.hstack([sub4, sub5]))

concateno verticalmente: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]] 

concateno orizzontalmente:
 [[ 1  2  1  2]
 [ 3  4  7  8]
 [ 5  6 13 14]
 [ 7  8 19 20]
 [ 9 10 25 26]
 [11 12 31 32]]
