# ESERCIZIO PROVA - Lezione del 07-10 (SLIDE 3)

## Array Slicing: Accessing Subarrays

### One-dimensional subarrays

Cambiare l’array creandone uno sempre di 10 valori ma che parta da 5 fino a 15 (escluso)

In [5]:
import numpy as np

es1 = np.arange(5,15)
es1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

1. primi sei valori
2. elementi dopo l’indice 3
3. elementi dopo il terzo elemento
4. subarray con valori 8,9,10,11,12
5. un elemento ogni tre, partendo dal primo
6. un elemento ogni tre partendo dal terzo elemento

In [10]:
#punto1
es1[0:6]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
#punto2
print("elemento di indice 3:", es1[3]),
print("elementi dopo indice 3:", es1[4:])

elemento di indice 3: 8
elementi dopo indice 3: [ 9 10 11 12 13 14]


In [18]:
#punto3
print("elementi dopo il terzo elemento:", es1[3:])

elementi dopo il terzo elemento: [ 8  9 10 11 12 13 14]


In [22]:
#punto4
es1[3:8]

array([ 8,  9, 10, 11, 12])

In [24]:
#punto5: per prendere un elemento ogni 3 quindi 5, 8, 11 e 14 posso usare la seguente funzione
es1[::3]
#::3 significa che li prende con step ogni 3

array([ 5,  8, 11, 14])

In [25]:
#punto6
es1[2::3]

array([ 7, 10, 13])