# ESERCIZIO PROVA - Lezione del 08-10 (SLIDE 5)
## Multi-dimensional subarrays

Creare un array es2a di valori casuali interi (randint) di dimensione 4x6, con
valore massimo (incluso) uguale a 15:

In [3]:
import numpy as np

es2a = np.random.randint(16, size=(4,6))
es2a

array([[ 9, 14, 10,  9, 13, 14],
       [14, 14, 15, 14, 12, 12],
       [ 9, 15,  5,  4, 15,  8],
       [14, 12, 11,  5, 12,  9]])

1. prime tre righe, prime tre colonne
2. seconda e terza riga, quarta, quinta e sesta colonna
3. elementi dopo il terzo elemento
4. invertire l’ordine delle sole righe; invertire l’ordine delle sole colonne

In [4]:
#punto1
es2a[:3, :3]

array([[ 9, 14, 10],
       [14, 14, 15],
       [ 9, 15,  5]])

In [7]:
#punto2
es2a[1:3, 3:6]

array([[14, 12, 12],
       [ 4, 15,  8]])

In [8]:
#punto3
es2a[3:, 3:]

array([[ 5, 12,  9]])

In [11]:
#punto4 ("\n" significa l'invio altrimenti viene tutto attaccato)
print("Array non invertito: \n", es2a, "\n")
print("Inverto le righe: \n", es2a[::-1,:], "\n")
print("Inverto le colonne: \n", es2a[:, ::-1], "\n")

Array non invertito: 
 [[ 9 14 10  9 13 14]
 [14 14 15 14 12 12]
 [ 9 15  5  4 15  8]
 [14 12 11  5 12  9]] 

Inverto le righe: 
 [[14 12 11  5 12  9]
 [ 9 15  5  4 15  8]
 [14 14 15 14 12 12]
 [ 9 14 10  9 13 14]] 

Inverto le colonne: 
 [[14 13  9 10 14  9]
 [12 12 14 15 14 14]
 [ 8 15  4  5 15  9]
 [ 9 12  5 11 12 14]] 



Creare un array es2b di valori casuali interi (randint) composto da due subarray di dimensione 5x5,
con valore massimo (incluso) uguale a 30.

In [13]:
es2b = np.random.randint(31, size=(2,5,5))
es2b

array([[[ 4, 24, 28, 18,  6],
        [14, 29, 17,  2, 17],
        [23, 11, 30,  3, 25],
        [26, 19, 20, 12, 16],
        [20, 17, 20,  9, 21]],

       [[26, 14, 13, 27,  3],
        [14,  7,  6,  0, 17],
        [15, 28,  9, 14,  1],
        [ 5, 25, 25,  1, 25],
        [29, 14, 23, 13,  3]]])

1. selezionare il primo subarray, da quello le prime 2 righe e le colonne dalla seconda
alla quarta.
2. selezionare da entrambi i subarray le prime due righe e prime due colonne e
invertire righe e colonne

In [17]:
#punto1
es2b[:1,:2,1:4]

array([[[24, 28, 18],
        [29, 17,  2]]])

In [18]:
#punto2
a=es2b[:,:2,:2]
print("Subarray 2x2 non invertiti: \n", a, "\n")
print("Inverto le righe: \n", a[:, ::-1, :], "\n")
print("Inverto le colonne: \n", a[:, :, ::-1], "\n")
print("Inverto righe e colonne:\n", a[:, ::-1, ::-1], "\n")

Subarray 2x2 non invertiti: 
 [[[ 4 24]
  [14 29]]

 [[26 14]
  [14  7]]] 

Inverto le righe: 
 [[[14 29]
  [ 4 24]]

 [[14  7]
  [26 14]]] 

Inverto le colonne: 
 [[[24  4]
  [29 14]]

 [[14 26]
  [ 7 14]]] 

Inverto righe e colonne:
 [[[29 14]
  [24  4]]

 [[ 7 14]
  [14 26]]] 

